import { Inter } from "next/font/google";
import "@styles/globals.css";
import themeConfig from "@config/theme.config";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const theme = themeConfig.theme || "base";
  const darkMode = themeConfig.enableDark ? "true" : "false";
  return (
    <html lang="en" data-theme={theme} data-dark={darkMode}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
